[package]
name = "tms_portal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.5", features = ["cookie", "cookie-private", "typed-header"] }
base64 = "0.22.1"
chrono = "0.4.45"
http = "1.4.2"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
jwtk = { version = "0.5.0", features = ["openssl"] }
reqwest = { version = "0.13.2", features = ["form"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["default", "arbitrary_precision"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono", "uuid"] }
tms_lib = { path = "../libraries/tms_lib"}
tms_proc_macros = { path = "../libraries/tms_proc_macros"}
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6.8", features = ["trace", "fs"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
url = "2.5.8"
uuid = { version = "1.22.0", features = ["v4"] }
rand = {  version = "0.10.2", features = ["thread_rng"] }

# had to run this command to get the build to work.  I guess there are issues with 0.3.48 with cookies library.
# this will fix it.
# cargo update -p time --precise 0.3.47
