openapi: 3.1.0
info:
  title: TMS portal server
  description: TMS portal server documentation
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development
  - url: https://tms-auth-service.tacc.cloud
    description: Development Server

paths:
  "/login":
    post:
      tags:
        - Login
      summary: Login
      description: Login to TMS Portal using specified identity provider, and redirect back to redirect uri (must be |
        configured as an allowed redirect uri)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TmsLoginRequest'
      responses:
        "307":
          description: Temporary redirect
          headers:
            location:
              schema:
                type: string
              description: redirect url
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TmsErrorResponse'

  "/login/whoami":
    get:
      tags:
        - Login
      summary: whoami
      security:
        - Bearer: [ ]
      description: Get information about logged in user
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TmsWhoAmIResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TmsErrorResponse'

  "/login/idps":
    get:
      tags:
        - Login
      summary: listIdps
      description: Get list of all supported login identity providers
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLoginIdpResponse'

  "/login/callback":
    get:
      tags:
        - Login
      summary: callback
      description: Called by identity provider with code that can be exchanged for a token.
      parameters:
        - name: code
          schema:
            type: string
          in: query
        - name: state
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TmsCallbackResponse'

  "/resources/{provider_id}":
    get:
      tags:
        - Resource
      summary: listResources
      description: Get a list of the resources for a given provider
      security:
        - Bearer: [ ]
      parameters:
        - name: provider_id
          in: path
          required: true
          description: The id of the provider to list resource for
          schema:
            type: string

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResourcesResponse'

  "/resources/providers":
    get:
      tags:
        - Resource
      summary: getResourceProviders
      description: Get a list of the resource providers
      security:
        - Bearer: [ ]
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResourceProvidersResponse'

  "/resources/providers/authorize":
    post:
      tags:
        - Resource
      summary: authorizeWithResourceProvider
      description: Authorization for a resource provider
      security:
        - Bearer: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceProviderAuthorizeRequest'

      responses:
        "307":
          description: Temporary redirect
          headers:
            location:
              schema:
                type: string
              description: redirect url
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TmsErrorResponse'

# ------------------------------------------------------------------------------
# --- Components ---------------------------------------------------------------
# ------------------------------------------------------------------------------
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # ------------------------------------------------------------------------------
    # --- Model objects ------------------------------------------------------------
    # ------------------------------------------------------------------------------
    TmsErrorResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: string

    TmsWhoAmIResponse:
      type: object
      properties:
        status:
          type: string
        result:
          properties:
            name:
              type: string
            user_name:
              type: string
            idpDisplayName:
              type: string
            organization:
              type: string
    
    
    TmsLoginRequest:
      required:
        - idp_id
        - redirect_uri
      type: object
      properties:
        idp_id:
          type: string
        redirect_uri:
          type: string

    ListLoginIdpResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/IdentityProvider'

    ListResourcesResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/Resource'

    ListResourceProvidersResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: array
          items:
            $ref: '#/components/schemas/IdentityProvider'

    TmsCallbackResponse:
      type: object
      properties:
        status:
          type: string
        result:
          properties:
            token:
              type: string

    IdentityProvider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        clientId:
          type: string
        oauth2TokenUrl:
          type: string
        userInfoUrl:
          type: string

    Resource:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        provider_id:
          type: string
        provider_name:
          type: string

    ResourceProviderAuthorizeRequest:
      type: object
      properties:
        provider_id:
          type: string
        redirect_url:
          type: string

